version: "3.8"
services:
  gitlab:
    image: gitlab/gitlab-ce:17.11.1-ce.0
    container_name: gitlab-ce
    hostname: gitlab.local
    ports:
      - "8080:80"
      - "8443:443"
      - "2224:22"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

  gerrit:
    image: gerritcodereview/gerrit:3.11.1
    container_name: gerrit
    ports:
      - "8090:8080"
      - "29418:29418"
    environment:
      - GERRIT_CONFIG_MAIL=false
      - GERRIT_CONFIG_SENDEMAIL_ENABLE=false
    volumes:
      - gerrit-data:/var/gerrit/etc
      - gerrit-git-volume:/var/gerrit/git
      - gerrit-index-volume:/var/gerrit/index
      - gerrit-cache-volume:/var/gerrit/cache

  # db:
  #   image: postgres:15
  #   container_name: code-review-db
  #   environment:
  #     POSTGRES_DB: mydb
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - code-review-db-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  # backend:
  #   build:
  #     context: ./backend/db-pcr-backend
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #     - gitlab
  #     - gerrit
  #   ports:
  #     - "8081:8081"

  # frontend:
  #   build:
  #     context: ./frontend/db-pcr-frontend
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - backend
  #   ports:
  #     - "4200:80"

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  gerrit-data:
  gerrit-git-volume:
  gerrit-index-volume:
  gerrit-cache-volume:
  code-review-db-data:
